name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
      - uses: actions/setup-python@v6
        with:
          cache: pip
          python-version-file: pyproject.toml
      - name: Install uv
        run: pip install uv
      - name: Install dependencies
        run: uv sync
      - name: Install clean-css
        run: npm install -g clean-css-cli
      - name: Build site
        run: uv run pelican content -s publishconf.py
      - name: Clean up
        run: rm -r output/theme/.webassets-cache
      - uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: gh-pages
          folder: output
